home:
    path:     /
    defaults: { _controller: StoreBundle:Shop:showProducts }
    
category:
    path:    /i/{name}
    defaults: { _controller: StoreBundle:Shop:showProducts }
    
add_template:
    path:   /admin/add/{type}
    defaults: { _controller: StoreBundle:Admin:showForm, id: null, action: add}
    
processing_form:
    path:   /admin/processing
    defaults: { _controller: StoreBundle:Admin:processingForm}
    
edit_template:
    path:   /admin/edit/{type}/{id}
    defaults: { _controller: StoreBundle:Admin:showForm, action: edit}    
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile    